{% set version = "0.4.0" %}

package:
  name: oxrdflib
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/o/oxrdflib/oxrdflib-{{ version }}.tar.gz
    sha256: 37d4c025d4e39c5e5472527c393998bfd10e5ac185a30e080b5b510f6dd7da86
  - folder: src
    url: https://github.com/oxigraph/oxrdflib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 0087953385e51ea1e268bf632f895956c5de1f8fd4f0af21b097ab80fd237d86

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - pyoxigraph >=0.3.14,<0.4
    - python >=3.7
    - rdflib >=6.3,<8.0

test:
  source_files:
    - src/tests
  imports:
    - oxrdflib
  commands:
    - pip check
    - cd src && pytest -vv --cov=oxrdflib --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=84
  requires:
    - pip
    - pytest-cov
    - requests

about:
  home: https://github.com/oxigraph/oxrdflib
  summary: rdflib stores based on pyoxigraph
  dev_url: https://github.com/oxigraph/oxrdflib
  license: BSD-3-Clause
  license_file: src/LICENSE.md

extra:
  recipe-maintainers:
    - bollwyvl
