{% set version = "0.4.0" %}

package:
  name: oxrdflib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/oxrdflib/oxrdflib-{{ version }}.tar.gz
  sha256: 37d4c025d4e39c5e5472527c393998bfd10e5ac185a30e080b5b510f6dd7da86

build:
  number: 0
  noarch: python
  script: 
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
  run:
    - pyoxigraph >=0.4.2,<0.5
    - python >=3.8
    - rdflib >=6.3,<8.0

test:
  source_files:
    - tests
  imports:
    - oxrdflib
  commands:
    - pip check
    - coverage run --source=oxrdflib --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered  --fail-under=87
  requires:
    - coverage
    - pip
    - pytest
    - requests

about:
  home: https://github.com/oxigraph/oxrdflib
  summary: rdflib stores based on pyoxigraph
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bollwyvl
