{% set version = "0.5.0" %}

package:
  name: oxrdflib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/oxrdflib/oxrdflib-{{ version }}.tar.gz
  sha256: f83148e2c6d443f7718c6e8936c6b89e36ebb4f1002da69e8f0656e8fb5a0df2

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - pyoxigraph >=0.4.2,<0.5
    - python >={{ python_min }}
    - rdflib >=6.3,<8.0

test:
  source_files:
    - tests
  imports:
    - oxrdflib
  commands:
    - pip check
    - coverage run --source=oxrdflib --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered  --fail-under=87
  requires:
    - coverage
    - pip
    - pytest
    - requests
    - python {{ python_min }}

about:
  home: https://github.com/oxigraph/oxrdflib
  summary: rdflib stores based on pyoxigraph
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bollwyvl
