# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.5.0

package:
  name: oxrdflib
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/oxrdflib/oxrdflib-${{ version }}.tar.gz
    sha256: f83148e2c6d443f7718c6e8936c6b89e36ebb4f1002da69e8f0656e8fb5a0df2
    target_directory: dist
  - url: https://github.com/oxigraph/oxrdflib/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 616a46f1000c8d6b84bb9b2e5a1c62bc8ec4b200217b67bc1cdced5cd749e99a
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build >=0.7,<0.9
  run:
    - pyoxigraph >=0.5,<0.6
    - python >=${{ python_min }}
    - rdflib >=6.3,<8.0

tests:
  - python:
      imports: oxrdflib
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - coverage
        - pytest
        - requests
        - python ${{ python_min }}.*
    script:
      - cd src
      - coverage run --source=oxrdflib --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered  --fail-under=87

about:
  summary: rdflib stores based on pyoxigraph
  license: BSD-3-Clause
  license_file: src/LICENSE.md
  homepage: https://github.com/oxigraph/oxrdflib

extra:
  recipe-maintainers:
    - bollwyvl
